### ISSUE TITLE
Moment node throws "TypeError: expandFormat"

### ISSUE THREAD

**Issue by M0ebiu5** [TotallyInformation/node-red-contrib-moment#13]
The moment node does not work in my installation (linux 4.4.0, node 4.8.3, node-red 16.2)

If i feed a timestamp into the node, it throws the error:
[error] [moment:3de373c3.2394ec] TypeError: expandFormat(...).match is not a function

**Comment by Fulvio1981** [comment]
I found the same anomaly with a  jessie lite (april 2017) installation where I've added just node-red (v0.16.2) and some additional node including node-red-contrib-moment (v2.0.5).
I've downgraded to v2.0.3 copying this folders from another SD card made some weeks ago (moment, moment-parseformat, moment-timezone, node-red-contrib-moment, os-locale) and now it's run perfectly.

In my opinion is something missing in repository with the last version because I've compared folder content between v2.0.5 and v2.0.3 and there is many files missing in the new version.

**Comment by TotallyInformation** [comment]
Hi, can you post an example flow that fails please? I'll try to track down what is causing that. I've had no problems on my Pi nor on my Windows development PC.

**Comment by M0ebiu5** [comment]
Hi,
the node never worked here - the flow is just an inject node before the moment node.
It is a completely new installation - so maybe Fulvio is right and there are some components missing?

**Comment by TotallyInformation** [comment]
Can you run an npm install command inside the ~/.node-red/node_modules/node-red-contrib-moment folder? Just to see if that fixes it.

**Comment by M0ebiu5** [comment]
Sorry, no success...

Output of install:
```
node-red-contrib-moment@2.0.5 node-red-contrib-moment
├── moment-parseformat@2.2.0
├── moment-timezone@0.5.13
├── moment@2.18.1
└── os-locale@2.0.0 (lcid@1.0.0, mem@1.1.0, execa@0.5.1)
```

The fresh, unconfigured moment node brings the following error:
"TypeError: node.inTz.split is not a function"

After configuring:
"TypeError: expandFormat(...).match is not a function"

**Comment by TotallyInformation** [comment]
OK, I will check as soon as I get some time.

Just to be clear, you are injecting a timestamp, have you used any settings in moment?

Also, can you let me know what locale and timezone you are in? I've noticed that timezones in particular seem quite fragile in the upstream moment processing.

**Comment by M0ebiu5** [comment]
Here is a screenshot of the settings dialog:

![clipboard01](https://user-images.githubusercontent.com/9152698/26924571-bf905c78-4c46-11e7-8d53-77ed60d2d8df.jpg)

**Comment by robertsLando** [comment]
Same problem here after upgrading from 2.0.3 to 2.0.5 the node has stop working and always throws that error.

**Comment by M0ebiu5** [comment]
I tried to install an older version of the moment node, but the error resisted.

Also, the underlying moment.js is present more than once on my system (seems like multiple nodes bring their own). Maybe it's a side-effect with another node (but i dont know if thats even possible)?

**Comment by drmibell** [comment]
Using  raspbian (jessie) 2017-04-10, NR 16.2, and moment 2.05, I get the same error as the OP when injecting a timestamp. Injecting an empty string I get:
"The input property was NOT a recognisable date. Output will be a blank string"
I was expecting the current date/time, as per the documentation. Perhaps this will help your debugging.

**Comment by TotallyInformation** [comment]
Hi all, apologies for this, not sure why it has stopped working but I'm looking at it now.

**Comment by TotallyInformation** [comment]
OK, I've found the problem. A subtle change in MomentJS meant that the parameter order had changed in one specific case. I've fixed it and will be pushing a new version shortly.

**Comment by TotallyInformation** [comment]
Fix is pushed and new npm version published.
